name: update json

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # 每天 UTC/GMT+08:00 凌晨 2 点检查更新
    - cron: '0 18 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: taffy-pvp-card-ds

      - name: Checkout enka
        uses: actions/checkout@v3
        with:
          repository: EnkaNetwork/API-docs
          fetch-depth: 1
          path: enka
          sparse-checkout: |
            store/loc.json
            store/characters.json
    
      - name: Checkout GenshinData
        run: |
          git clone --depth 1 --filter=blob:none --sparse https://gitlab.com/Dimbreath/AnimeGameData.git GenshinData
          cd GenshinData
          git sparse-checkout add "ExcelBinOutput"
          git sparse-checkout add "TextMap"
          cd ..

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Update
        run: |
          cp -rf enka/store/loc.json taffy-pvp-card-ds/data/loc.json
          cd taffy-pvp-card-ds
          node index.js

      - name: Check & Push
        run: bash ./taffy-pvp-card-ds/pushUpdate.sh
        shell: bash
